
version: '3'
services:
  app:
    image: lesson-capture-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3100:3100
    restart: always

    networks:
      - shared_network

networks:
  shared_network:
    external: true
  
    